#!/usr/bin/env python3
"""
SRS Document Generator
Generates DOCX documents from selected headings and their content
"""

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml.shared import OxmlElement, qn
import os
from typing import List, Dict, Any
import openai
from openai import OpenAI

def generate_srs_docx(headings: List[Dict[str, Any]], output_path: str, uploaded_content: str = ""):
    """
    Generate SRS document in DOCX format from selected headings
    
    Args:
        headings: List of heading dictionaries with 'heading', 'purpose', 'category', 'source'
        output_path: Path where to save the generated DOCX file
        uploaded_content: Content from uploaded PDF documents for context
    """
    try:
        # Create a new document
        doc = Document()
        
        # Set up document styles
        setup_document_styles(doc)
        
        # Add title page
        add_title_page(doc)
        
        # Add table of contents
        add_table_of_contents(doc, headings)
        
        # Add content sections
        add_content_sections(doc, headings, uploaded_content)
        
        # Save the document
        doc.save(output_path)
        
        print(f"✅ SRS document generated successfully: {output_path}")
        
    except Exception as e:
        print(f"❌ Failed to generate SRS document: {str(e)}")
        raise

def setup_document_styles(doc: Document):
    """Set up document styles for consistent formatting"""
    try:
        # Title style
        title_style = doc.styles.add_style('SRS Title', WD_STYLE_TYPE.PARAGRAPH)
        title_font = title_style.font
        title_font.name = 'Arial'
        title_font.size = Pt(24)
        title_font.bold = True
        title_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_style.paragraph_format.space_after = Pt(12)
        
        # Heading 1 style
        h1_style = doc.styles.add_style('SRS Heading 1', WD_STYLE_TYPE.PARAGRAPH)
        h1_font = h1_style.font
        h1_font.name = 'Arial'
        h1_font.size = Pt(16)
        h1_font.bold = True
        h1_style.paragraph_format.space_before = Pt(12)
        h1_style.paragraph_format.space_after = Pt(6)
        
        # Heading 2 style
        h2_style = doc.styles.add_style('SRS Heading 2', WD_STYLE_TYPE.PARAGRAPH)
        h2_font = h2_style.font
        h2_font.name = 'Arial'
        h2_font.size = Pt(14)
        h2_font.bold = True
        h2_style.paragraph_format.space_before = Pt(10)
        h2_style.paragraph_format.space_after = Pt(6)
        
        # Normal text style
        normal_style = doc.styles.add_style('SRS Normal', WD_STYLE_TYPE.PARAGRAPH)
        normal_font = normal_style.font
        normal_font.name = 'Arial'
        normal_font.size = Pt(11)
        normal_style.paragraph_format.space_after = Pt(6)
        
    except Exception as e:
        print(f"⚠️ Warning: Could not set up custom styles: {e}")

def add_title_page(doc: Document):
    """Add title page to the document"""
    # Add title
    title = doc.add_paragraph('Software Requirements Specification', style='SRS Title')
    
    # Add subtitle
    subtitle = doc.add_paragraph('Generated by SRS Dynamic Generator', style='SRS Normal')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add some spacing
    doc.add_paragraph()
    doc.add_paragraph()
    
    # Add document info
    info_para = doc.add_paragraph('Document Information:', style='SRS Heading 2')
    info_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    
    # Add document details
    details = [
        ('Document Type:', 'Software Requirements Specification'),
        ('Generated Date:', 'Auto-generated'),
        ('Tool:', 'SRS Dynamic Generator'),
        ('Version:', '1.0')
    ]
    
    for label, value in details:
        detail_para = doc.add_paragraph(f'{label} {value}', style='SRS Normal')
    
    # Add page break
    doc.add_page_break()

def add_table_of_contents(doc: Document, headings: List[Dict[str, Any]]):
    """Add table of contents to the document"""
    # Add TOC title
    toc_title = doc.add_paragraph('Table of Contents', style='SRS Heading 1')
    toc_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Separate custom sections from other headings
    custom_sections = []
    other_headings = []
    
    for heading in headings:
        if heading.get('category') == 'Custom':
            custom_sections.append(heading)
        else:
            other_headings.append(heading)
    
    # Group non-custom headings by category
    categories = {}
    for heading in other_headings:
        category = heading.get('category', 'Other')
        if category not in categories:
            categories[category] = []
        categories[category].append(heading)
    
    # Add TOC entries for categorized headings
    for category, category_headings in categories.items():
        # Add category header
        category_para = doc.add_paragraph(category, style='SRS Heading 2')
        
        # Add headings in this category
        for i, heading in enumerate(category_headings, 1):
            heading_text = heading.get('heading', '')
            toc_entry = doc.add_paragraph(f'{i}. {heading_text}', style='SRS Normal')
            toc_entry.paragraph_format.left_indent = Inches(0.5)
    
    # Add custom sections as individual TOC entries (no category grouping)
    if custom_sections:
        # Add a separator or header for custom sections
        custom_header = doc.add_paragraph('Custom Sections', style='SRS Heading 2')
        
        # Add each custom section as individual entry
        for i, custom_heading in enumerate(custom_sections, 1):
            heading_text = custom_heading.get('heading', '')
            toc_entry = doc.add_paragraph(f'{i}. {heading_text}', style='SRS Normal')
            toc_entry.paragraph_format.left_indent = Inches(0.5)
    
    # Add page break
    doc.add_page_break()

def add_content_sections(doc: Document, headings: List[Dict[str, Any]], uploaded_content: str = ""):
    """Add content sections for each heading"""
    # Separate custom sections from other headings
    custom_sections = []
    other_headings = []
    
    for heading in headings:
        if heading.get('category') == 'Custom':
            custom_sections.append(heading)
        else:
            other_headings.append(heading)
    
    # Group non-custom headings by category
    categories = {}
    for heading in other_headings:
        category = heading.get('category', 'Other')
        if category not in categories:
            categories[category] = []
        categories[category].append(heading)
    
    # Add content for each category (excluding custom sections)
    for category, category_headings in categories.items():
        # Add category header
        category_para = doc.add_paragraph(category, style='SRS Heading 1')
        
        # Add content for each heading in this category
        for heading in category_headings:
            add_heading_content(doc, heading, uploaded_content)
        
        # Add some spacing between categories
        doc.add_paragraph()
    
    # Add custom sections as individual sections (no category grouping)
    for custom_heading in custom_sections:
        add_heading_content(doc, custom_heading, uploaded_content)
        # Add spacing between custom sections
        doc.add_paragraph()

def add_heading_content(doc: Document, heading: Dict[str, Any], uploaded_content: str = ""):
    """Add content for a specific heading"""
    heading_text = heading.get('heading', '')
    purpose = heading.get('purpose', '')
    source = heading.get('source', 'Unknown')
    category = heading.get('category', 'Other')
    user_prompt = heading.get('userPrompt', '')
    # Add heading
    heading_para = doc.add_paragraph(heading_text, style='SRS Heading 2')
    # Add purpose
    if purpose:
        purpose_para = doc.add_paragraph(f'Purpose: {purpose}', style='SRS Normal')
        purpose_para.paragraph_format.left_indent = Inches(0.25)
    # Add source information
    source_para = doc.add_paragraph(f'Source: {source}', style='SRS Normal')
    source_para.paragraph_format.left_indent = Inches(0.25)
    source_para.paragraph_format.space_after = Pt(12)
    # Generate content using AI with uploaded document context and user_prompt
    generated_content = generate_content_for_heading(
        heading_text,
        purpose,
        source,
        uploaded_content,
        user_prompt
    )
    # Add generated content
    content_para = doc.add_paragraph(generated_content, style='SRS Normal')
    content_para.paragraph_format.left_indent = Inches(0.25)
    content_para.paragraph_format.space_after = Pt(12)

def generate_content_for_heading(heading: str, purpose: str, source: str, uploaded_content: str = "", user_prompt: str = "") -> str:
    """
    Generate content for a heading using AI, with optional user_prompt
    """
    try:
        if not os.getenv('OPENAI_API_KEY'):
            print("❌ Error: OPENAI_API_KEY not found. Cannot generate SRS content without AI.")
            return f"Error: OpenAI API key not configured. Cannot generate content for '{heading}'. Please set OPENAI_API_KEY environment variable."
        client = OpenAI()
        if user_prompt and user_prompt.strip():
            prompt = f"""
            USER INSTRUCTIONS:
            {user_prompt}
            SECTION HEADING: {heading}
            MEETING TRANSCRIPT CONTEXT:
            {uploaded_content if uploaded_content else "No meeting transcript available for context."}
            """
        else:
            prompt = f"""
            You are professional SRS writer of MSBC Group company and writing SRS for that company, Don't write any content as 'according to meeting transcript', Generate only content which is relevant to the SRS.
            Generate detailed professional content for an SRS (Software Requirements Specification) section based on the meeting transcript provided.
            SECTION HEADING: {heading}
            MEETING TRANSCRIPT CONTEXT:
            {uploaded_content if uploaded_content else "No meeting transcript available for context."}
            CRITICAL REQUIREMENTS:
            1. Generate MINIMUM 5-7 paragraphs for this section
            2. Each paragraph must be substantial (at least 2-3 sentences)
            3. Total content should be 300-500 words minimum
            4. Use clear, professional language suitable for SRS documentation
            CRITICAL INSTRUCTIONS:
            1. ONLY use information from the meeting transcript above - do not make up generic content
            2. Reference specific discussions, decisions, and requirements mentioned in the meeting
            3. Use exact project names, technologies, and requirements mentioned in the transcript
            4. If the meeting discusses specific features, systems, or requirements related to this heading, include those details
            5. Base your content on actual meeting discussions, not generic SRS templates
            CONTENT STRUCTURE:
            - Start with a brief overview of what this section covers based on meeting discussions
            - Include specific requirements mentioned in the meeting
            - Reference any decisions made during the meeting
            - Include any technical specifications discussed
            - Mention any constraints or considerations raised in the meeting
            EXAMPLES:
            - If the meeting discussed \"user authentication\", write about the specific authentication requirements mentioned
            - If the meeting mentioned \"database design\", include the specific database requirements discussed
            - If the meeting talked about \"API endpoints\", include the specific API requirements mentioned
            Write in a clear, professional format suitable for SRS documentation. Each paragraph should be substantial and informative, drawing directly from the meeting transcript above.
            """
        response = client.chat.completions.create(
            model="gpt-4.1-nano",
            messages=[
                {"role": "system", "content": "You are an expert software requirements analyst and technical writer. Generate detailed, professional content for SRS documents based on uploaded meeting summaries and requirements."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=2048,
            temperature=0.7,
        )
        content = response.choices[0].message.content.strip()
        return content
    except Exception as e:
        print(f"❌ Error generating content for heading '{heading}': {e}")
        return f"Error generating content for '{heading}': {str(e)}"



def add_page_number(paragraph):
    """Add page number to a paragraph"""
    run = paragraph.add_run()
    fldChar1 = OxmlElement('w:fldChar')
    fldChar1.set(qn('w:fldCharType'), 'begin')
    
    instrText = OxmlElement('w:instrText')
    instrText.text = "PAGE"
    
    fldChar2 = OxmlElement('w:fldChar')
    fldChar2.set(qn('w:fldCharType'), 'end')
    
    run._r.append(fldChar1)
    run._r.append(instrText)
    run._r.append(fldChar2)

if __name__ == "__main__":
    # Test the generator
    test_headings = [
        {
            'heading': '1. Introduction',
            'purpose': 'Briefly describe the system and its main objectives',
            'category': 'Introduction',
            'source': 'Standard Template'
        },
        {
            'heading': '2. Functional Requirements',
            'purpose': 'Define the functional requirements of the system',
            'category': 'Requirements',
            'source': 'Standard Template'
        },
        {
            'heading': 'Custom Section',
            'purpose': 'This is a custom section added by the user',
            'category': 'Custom',
            'source': 'Custom Section'
        }
    ]
    
    generate_srs_docx(test_headings, 'test_srs.docx') 